lib/civ_bot_ex_web/router.ex
defmodule CivBotWeb.Router do
  use CivBotWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug CivBotWeb.Plugs.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", CivBotWeb do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
    post "/logout", AuthController, :delete
  end

  scope "/", CivBotWeb do
    pipe_through :browser

    get "/", PageController, :index

    scope "/user" do
      get "/", UserController, :show
      get "/edit", UserController, :edit
      put "/update", UserController, :update
      delete "/", UserController, :delete
    end

    # resources "/users", UserController, except: [:create]
    resources "/games", GameController
  end

  # Other scopes may use custom stacks.
  # scope "/api", CivBotWeb do
  #   pipe_through :api
  # end
end

lib/civ_bot_ex_web/views/layout_view.ex
defmodule CivBotWeb.LayoutView do
  use CivBotWeb, :view
end

lib/civ_bot_ex_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>CivBot · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if @current_user do %>
              <li><%= link "Logout", to: Routes.auth_path(@conn, :delete), method: :post %></li>
            <% else %>
              <li><%= link "Login", to: Routes.auth_path(@conn, :request, "discord") %></li>
            <% end %>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>